### ISSUE TITLE
Support type/pattern annotations in union types

### ISSUE THREAD

**Issue by kayahr** [YousefED/typescript-json-schema#225] opened 2018-07-12 13:43 UTC
tjs seems to ignore the type and pattern annotations when creating schema types for typescript union types.

Example:

```typescript
/**
 * @pattern ^#[0-9a-f]{6}$
 */
export type HTMLColor = string;

/**
 * @pattern ^rgba\(\d+,\d+,\d+,\d+\)$
 */
export type RGBAColor = string;

export type Color = HTMLColor | RGBAColor;

export interface Config {
    "color1": HTMLColor;
    "color2": RGBAColor;
    "color3": Color;
}
```

When creating a schema for the Config interface then this is the output:

```javascript
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "properties": {
        "color1": {
            "pattern": "^#[0-9a-f]{6}$",
            "type": "string"
        },
        "color2": {
            "pattern": "^rgba\\(\\d+,\\d+,\\d+,\\d+\\)$",
            "type": "string"
        },
        "color3": {
            "type": "string"
        }
    },
    "type": "object"
}
```

So the pattern annotation works for the first two color properties which use no union types. But `color3` which uses a union type with annotations doesn't work as expected.

Would be nice if tjs could use `anyOf` in this case so the schema allows both patterns instead of ignoring the patterns completely:

```javascript
"anyOf": [
    {
        "pattern": "^#[0-9a-f]{6}$",
        "type": "string"
    },
    {
        "pattern": "^rgba\\(\\d+,\\d+,\\d+,\\d+\\)$",
        "type": "string"
    }
]
```

**Comment by domoritz** [comment] 2018-07-12 14:09
You can add a comment to the unioned type instead. `anyOf` unfortunately had different semantics and breaks if you want to use properties from both unioned types. 

The only solution I see is to automatically merge the two comments but that sounds like a nightmare for larger projects. 

I'm closing this to be by design.

**Comment by domoritz** [comment] 2018-07-12 14:10
Once json schmea supports proper union, intersection, and extend, this will change.

**Closed by domoritz** 2018-07-12 14:09 UTC
